series: Intermediate C++
title: Enums
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use enums to define custom data types with specific values for your program.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Classes and Structs
  - series: Basic C++
    title: The Const Keyword
  - series: Intermediate C++
    title: Bitwise Operators